let data = [
    {
        id: 1,
        image: "/images/card.jpg",
        type: "shirt",
        title: "Dennis Lingo",
        para1: "Men's Checkered Cotton Formal Shirt",
        paraSmall1: "+17 colors/patterns",
        price: 1399,
        priceDel:"2,549",
        priceDiscount:"64",
        totalquantity: 6,
    },
    {
        id: 2,
        image: "/images/card-4.jpg",
        type: "shirt",
        title: "Diverse",
        para1: "Men's Regular fit Formal Shirt",
        paraSmall1: "+11 colors/patterns",
        price: 439,
        priceDel:"899",
        priceDiscount:"51",
        totalquantity: 5,
    },
    {
        id: 3,
        image: "/images/card-2.jpg",
        type: "shirt",
        title: "MARK & ALBERT",
        para1: "Men's Solid Regular Fit Casual Shirt",
        paraSmall1: "+15 colors/patterns",
        price: 599,
        priceDel:"1,199",
        priceDiscount:"78",
        totalquantity: 10,
    },
    {
        id: 4,
        image: "/images/card-3.jpeg",
        title: "Ben Martin",
        type: "shirt",
        para1: "Men's Slim Fit Casual Shirt",
        paraSmall1: "+14 colors/patterns",
        price: 799,
        priceDel:"1,575",
        priceDiscount:"59",
        totalquantity: 7,
    },
    {
        id: 5,
        image: "/images/card-9.jpg",
        type: "pant",
        title: "TAILRED",
        para1: "Men's Regular Fit Poly Cotton Track Pant",
        paraSmall1: "+9 colors/patterns",
        price: 1609,
        priceDel:"3,199",
        priceDiscount:"32",
        totalquantity: 12,
    },
    {
        id: 6,
        image: "/images/card-10.jpg",
        type: "pant",
        title: "Amazon Brand - Symbol",
        para1: "Men's Regular Casual Trousers",
        paraSmall1: "+5 colors/patterns",
        price: 579,
        priceDel:"1,299",
        priceDiscount:"54",
        totalquantity: 14,
    },
    {
        id: 7,
        image: "/images/card-11.jpg",
        type: "pant",
        title: "Chromozome",
        para1: "Men's Regular Fit Track pants",
        paraSmall1: "+14 colors/patterns",
        price: 599,
        priceDel:"999",
        priceDiscount:"40",
        totalquantity: 20,
    },
    {
        id: 8,
        image: "/images/card-12.jpg",
        type: "pant",
        title: "MARK LOUIIS",
        para1: "Men's Regular Fit Trackpants",
        paraSmall1: "+10 colors/patterns",
        price: 699,
        priceDel:"1,499",
        priceDiscount:"53",
        totalquantity: 16,
    },
];

export default data;